security:
  user:
    password: password
logging:
  level:
    org.springframework.security: DEBUG
spring.datasource:
  url: jdbc:mysql://localhost:3306/realperfect
  username: root
  password: root
  driverClassName: com.mysql.jdbc.Driver
spring:
  http:
    multipart.max-file-size: 5MB
  jpa:
    show-sql: true


NotEmpty: This field is required.
Size.userForm.username: Please use between 6 and 32 characters.
Duplicate.userForm.username: Someone already has that username.
Size.userForm.password: Try one with at least 6 characters.
Diff.userForm.passwordConfirm: These passwords don't match.